maping through nested rules
artf/grapesjs pull request #2935
Opened 2020-08-03 07:27 UTC by makbari

This is integration of the nested rules. When nested at rules is parsed from grapesjs-parset-postcss, grapes js resolve them. 
an example is also provided in the postcss repo.

2020-08-26 15:29 UTC, artf requested changes
Can you please explain the point of this PR? What are you trying to solve?

2020-08-26 15:29 UTC, artf commented on src/code_manager/model/CssGenerator.js
> +    let isGjsRule = false;
what is the point of this variable? Seems like you don't use it...

2020-08-26 15:29 UTC, artf commented on src/parser/model/BrowserParserCss.js
> +const singleAtRulesNames = ['font-face', 'counter-style', 'viewport'];
Why did you remove the `page`?

2020-08-26 15:29 UTC, artf commented on src/code_manager/model/CssGenerator.js
> +    if ((selectorStrNoAdd && found) || selectorsAdd || singleAtRule || rule.attributes.style) {
`rule.attributes.style` is an object, it's a truthy value, so the condition is pointless

2020-08-26 15:29 UTC, artf commented on src/code_manager/model/CssGenerator.js
> +      const block = rule.getDeclaration().length > 0 ? rule.getDeclaration() : styleStr;
You're calling rule.getDeclaration() twice and honestly, I don't understand the point of this change

2020-08-31 12:13 UTC, makbari commented
Thanks for the review. I will make some correction and more updates. 
There problem I am trying to solve is that, page at rule, can have nested at rule. 
The example is also in https://github.com/artf/grapesjs-parser-postcss/pull/1

2022-02-06 05:22 UTC, closed without merging